name: gurugranth
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  appwrite: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/fonts/

  fonts:
    - family: AnekMalayalam
      fonts:
        - asset: assets/fonts/AnekMalayalam-Bold.ttf
          weight: 700
        - asset: assets/fonts/AnekMalayalam_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/AnekMalayalam_Condensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AnekMalayalam_Condensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/AnekMalayalam_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/AnekMalayalam_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/AnekMalayalam_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/AnekMalayalam_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AnekMalayalam_Condensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/AnekMalayalam_Expanded-Bold.ttf
          weight: 700
        - asset: assets/fonts/AnekMalayalam_Expanded-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AnekMalayalam_Expanded-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/AnekMalayalam_Expanded-Light.ttf
          weight: 300
        - asset: assets/fonts/AnekMalayalam_Expanded-Medium.ttf
          weight: 500
        - asset: assets/fonts/AnekMalayalam_Expanded-Regular.ttf
          weight: 400
        - asset: assets/fonts/AnekMalayalam_Expanded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AnekMalayalam_Expanded-Thin.ttf
          weight: 100
        - asset: assets/fonts/AnekMalayalam-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AnekMalayalam-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/AnekMalayalam-Light.ttf
          weight: 300
        - asset: assets/fonts/AnekMalayalam-Medium.ttf
          weight: 500
        - asset: assets/fonts/AnekMalayalam-Regular.ttf
          weight: 400
        - asset: assets/fonts/AnekMalayalam-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AnekMalayalam_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/AnekMalayalam_SemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AnekMalayalam_SemiCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/AnekMalayalam_SemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/AnekMalayalam_SemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/AnekMalayalam_SemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/AnekMalayalam_SemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AnekMalayalam_SemiCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/AnekMalayalam_SemiExpanded-Bold.ttf
          weight: 700
        - asset: assets/fonts/AnekMalayalam_SemiExpanded-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AnekMalayalam_SemiExpanded-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/AnekMalayalam_SemiExpanded-Light.ttf
          weight: 300
        - asset: assets/fonts/AnekMalayalam_SemiExpanded-Medium.ttf
          weight: 500
        - asset: assets/fonts/AnekMalayalam_SemiExpanded-Regular.ttf
          weight: 400
        - asset: assets/fonts/AnekMalayalam_SemiExpanded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AnekMalayalam_SemiExpanded-Thin.ttf
          weight: 100
        - asset: assets/fonts/AnekMalayalam-Thin.ttf
          weight: 100